services:
  db:
    image: postgres:15
    container_name: countdown-hub-db
    environment:
      POSTGRES_USER: countdown_user
      POSTGRES_PASSWORD: countdown_pass
      POSTGRES_DB: countdown_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: countdown-hub-backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://countdown_user:countdown_pass@db:5432/countdown_hub
      PORT: 3001
      PRISMA_CLI_BINARY_TARGETS: debian-openssl-3.0.x
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: countdown-hub-frontend
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data: