services:
  - type: web
    name: countdown-hub-api
    env: node
    buildCommand: npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: countdown-hub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false
      - key: FRONTEND_URL
        value: https://countdownhub.jp
    healthCheckPath: /health

databases:
  - name: countdown-hub-db
    databaseName: countdown_hub
    user: countdown_user